BLOCK_GITHUB_LINK="https://github.com/AKafakA/Block.git"
VLLM_GITHUB_LINK="https://github.com/AKafakA/vllm.git"

# Fix Ubuntu mirror (us.archive.ubuntu.com can be unreachable from CloudLab) and enable universe repo (needed for python3-pip)
parallel-ssh -t 0 -h block/config/hosts "sudo sed -i 's|us.archive.ubuntu.com|mirrors.edge.kernel.org|g' /etc/apt/sources.list"
parallel-ssh -t 0 -h block/config/hosts "sudo sed -i 's|jammy restricted main|jammy restricted main universe|g; s|jammy-updates restricted main|jammy-updates restricted main universe|g; s|jammy-security restricted main|jammy-security restricted main universe|g' /etc/apt/sources.list"
parallel-ssh -t 0 -h block/config/hosts "sudo apt update"
parallel-ssh -t 0 -h block/config/hosts "sudo apt install -y python3-pip python3-venv ccache ninja-build"
parallel-ssh -t 0 -h block/config/hosts "pip3 install -U pip==25.0.1"
parallel-ssh -t 0 -h block/config/hosts "pip install uv"
parallel-ssh -t 0 -h block/config/hosts "wget -q https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin && sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600"
parallel-ssh -t 0 -h block/config/hosts "wget -q https://developer.download.nvidia.com/compute/cuda/12.6.3/local_installers/cuda-repo-ubuntu2004-12-6-local_12.6.3-560.35.05-1_amd64.deb && sudo dpkg -i cuda-repo-ubuntu2004-12-6-local_12.6.3-560.35.05-1_amd64.deb"
parallel-ssh -t 0 -h block/config/hosts "sudo cp /var/cuda-repo-ubuntu2004-12-6-local/cuda-*-keyring.gpg /usr/share/keyrings/ && sudo apt-get update"
parallel-ssh -t 0 -h block/config/hosts "sudo dpkg --configure -a && sudo apt-get -y install cuda-toolkit-12-6 && sudo apt-get install -y nvidia-open"
parallel-ssh -t 0 -h block/config/hosts "echo 'export PATH=\$PATH:/usr/local/cuda-12.6/bin' >> ~/.bashrc && echo 'export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/usr/local/cuda-12.6/lib64' >> ~/.bashrc && source ~/.bashrc"
parallel-ssh -t 0 -h block/config/hosts "sudo nvidia-smi -mig 0"
# vLLM: sudo install gets .so files, then uv registers proper metadata for user
parallel-ssh -t 0 -h block/config/hosts "git clone ${VLLM_GITHUB_LINK} && cd vllm && sudo VLLM_USE_PRECOMPILED=1 pip install --editable . && sudo chown -R \$(whoami) ~/vllm"
parallel-ssh -t 0 -h block/config/hosts "cd vllm && VLLM_USE_PRECOMPILED=1 ~/.local/bin/uv pip install -e . --no-deps --target ~/.local/lib/python3.10/site-packages"
parallel-ssh -t 0 -h block/config/hosts "git clone ${BLOCK_GITHUB_LINK} && cd Block && git checkout main && pip install -r requirements.txt"
parallel-ssh -t 0 -h block/config/hosts "rm -rf ~/cuda-repo-*.deb"
parallel-ssh -t 0 -h block/config/hosts "pip install torch==2.6.0 torchvision==0.21.0 torchaudio==2.6.0 --index-url https://download.pytorch.org/whl/cu126"
# flashinfer from official wheel index (PyPI 0.2.5 tarball has broken metadata)
parallel-ssh -t 0 -h block/config/hosts "pip install flashinfer-python -i https://flashinfer.ai/whl/cu124/torch2.6/"
parallel-ssh -t 0 -h block/config/hosts "pip install triton==3.2.0"
parallel-ssh -t 0 -h block/config/hosts "pip install transformers==4.50.3"
parallel-ssh -t 0 -h block/config/hosts "pip install ninja orjson"
